name: Build Android App Bundle

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Dependencies
        run: npm install

      - name: Build Web App & Sync Capacitor
        run: npm run build:android

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Generate Keystore
        working-directory: ./android/app
        run: keytool -genkey -v -keystore laya-release.keystore -alias laya -keyalg RSA -keysize 2048 -validity 10000 -storepass laya123 -keypass laya123 -dname "CN=Roshmusik, OU=Laya, O=Roshmusik, L=Kerala, S=Kerala, C=IN"

      - name: Build Android App Bundle
        working-directory: ./android
        run: ./gradlew bundleRelease -Pandroid.injected.signing.store.file=app/laya-release.keystore -Pandroid.injected.signing.store.password=laya123 -Pandroid.injected.signing.key.alias=laya -Pandroid.injected.signing.key.password=laya123

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Laya-Release-AAB
          path: android/app/build/outputs/bundle/release/*.aab
